AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AnswerKing API Gateway
  Sample SAM Template for basic-aws-apigateway-demo
  
Resources:
  AnswerKingApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Answer King API
      StageName: Development
  Psycopg2LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: psycopg2-lambda-layer
      ContentUri: ./api/layer-code/psycopg2.zip
      CompatibleRuntimes:
        - python3.11
  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./api/create.zip
      Handler: create.lambda_handler
      Layers: 
        - !Ref Psycopg2LambdaLayer
      Runtime: python3.11
      Events:
        AnswerKingApi:
          Type: Api
          Properties:
            RestApiId: !Ref AnswerKingApiGateway
            Path: /item
            Method: POST
 
Outputs:
  AnswerKingApiGateway:
    Description: 'API Gateway endpoint URL for Development stage for create item'
    Value: !Sub 'https://${AnswerKingApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Staging/hello/'
  AnswerKingAWSApiGatewayRestApiId:
    Description: 'API Gateway ARN for Answer King API'
    Value: !Ref AnswerKingApiGateway
    Export:
      Name: AnswerKingApiGateway-RestApiId
  AnswerKingApiGatewayRootResourceId:
    Value: !GetAtt AnswerKingApiGateway.RootResourceId
    Export:
      Name: AnswerKingApiGateway-RootResourceId