AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS infrastructure for AnswerKing API'

Parameters:
  Project:
    Type: String
    Default: "AnswerKing-API"
    Description: "Project name"
    
  Owner:
    Type: String
    Default: "jackson.macdonald@answerdigital.com"
    Description: "Resource owner"

  CostCentre:
    Type: String
    Default: "AnswerAcademy"
    Description: "Cost centre for tagging"
  
  ManagedBy:
    Type: String
    Default: "Cloudformation"

  DBUsername:
    Type: String
    NoEcho: true
  
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  AnswerKingDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBName: AnswerKingAPI
      Engine: postgres
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "20"
      DBInstanceIdentifier: AnswerKingDB
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      Tags:
        - Key: Name
          Value: AnswerKingDB
        - Key: Project
          Value: !Ref Project
        - Key: CostCentre
          Value: !Ref CostCentre
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Type
          Value: RDS
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: My DB Subnet Group
      SubnetIds: 
        - !ImportValue Subnet1ID
        - !ImportValue Subnet2ID
      Tags:
        - Key: Name
          Value: AnswerKingDBSubnetGroup
        - Key: Project
          Value: !Ref Project
        - Key: CostCentre
          Value: !Ref CostCentre
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Type
          Value: DBSubnetGroup
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: !ImportValue AnswerKingVPCID
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: LambdaSecurityGroup
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS
      VpcId: !ImportValue AnswerKingVPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 188.39.219.34/32
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
      Tags:
        - Key: Name
          Value: AnswerKingDBSecurityGroup
        - Key: Project
          Value: !Ref Project
        - Key: CostCentre
          Value: !Ref CostCentre
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Type
          Value: SecurityGroup

Outputs:
  LambdaSecurityGroupID:
    Description: Lambda Security Group ID
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: LambdaSecurityGroupID
  AnswerKingDBHost:
    Description: The database endpoint address
    Value: !GetAtt AnswerKingDB.Endpoint.Address
    Export:
      Name: AnswerKingDBHost