AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC for AnswerKing'

Parameters:
  Project:
    Type: String
    Default: "AnswerKing-API"
    Description: "Project name"
    
  Owner:
    Type: String
    Default: "jackson.macdonald@answerdigital.com"
    Description: "Resource owner"

  CostCentre:
    Type: String
    Default: "AnswerAcademy"
    Description: "Cost centre for tagging"
  
  ManagedBy:
    Type: String
    Default: "Cloudformation"

Resources:
  AnswerKingVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: AnswerKingVPC
        - Key: Project
          Value: !Ref Project
        - Key: CostCentre
          Value: !Ref CostCentre
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Type
          Value: VPC
  
  AnswerKingSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AnswerKingVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: AnswerKing-Subnet
        - Key: Project
          Value: !Ref Project
        - Key: CostCentre
          Value: !Ref CostCentre
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Type
          Value: Subnet

Outputs:
  AnswerKingVPCId:
    Description: AnswerKing VPC ID
    Value: !Ref AnswerKingVPC

  Subnet1Id:
    Description: AnswerKing Subnet ID
    Value: !Ref AnswerKingSubnet
