AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC for AnswerKing'

Parameters:
  Project:
    Type: String
    Default: "AnswerKing-API"
    Description: "Project name"
    
  Owner:
    Type: String
    Default: "jackson.macdonald@answerdigital.com"
    Description: "Resource owner"

  CostCentre:
    Type: String
    Default: "AnswerAcademy"
    Description: "Cost centre for tagging"
  
  ManagedBy:
    Type: String
    Default: "Cloudformation"

Resources:
  AnswerKingVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: AnswerKingVPC
        - Key: Project
          Value: !Ref Project
        - Key: CostCentre
          Value: !Ref CostCentre
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Type
          Value: VPC
  
  AnswerKingSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AnswerKingVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: eu-west-2b
      Tags:
        - Key: Name
          Value: AnswerKing-Subnet
        - Key: Project
          Value: !Ref Project
        - Key: CostCentre
          Value: !Ref CostCentre
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Type
          Value: Subnet
  AnswerKingSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AnswerKingVPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: eu-west-2a
      Tags:
        - Key: Name
          Value: AnswerKing-Subnet-2
        - Key: Project
          Value: !Ref Project
        - Key: CostCentre
          Value: !Ref CostCentre
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Type
          Value: Subnet

  AnswerKingInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: AnswerKingIGW
        - Key: Project
          Value: !Ref Project
        - Key: CostCentre
          Value: !Ref CostCentre
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Type
          Value: InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AnswerKingVPC
      InternetGatewayId: !Ref AnswerKingInternetGateway

  AnswerKingPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AnswerKingVPC
      Tags:
        - Key: Name
          Value: AnswerKingPublicRouteTable
        - Key: Project
          Value: !Ref Project
        - Key: CostCentre
          Value: !Ref CostCentre
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Type
          Value: RouteTable
  
  AnswerKingPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AnswerKingVPC
      Tags:
        - Key: Name
          Value: AnswerKingPrivateRouteTable
        - Key: Project
          Value: !Ref Project
        - Key: CostCentre
          Value: !Ref CostCentre
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: !Ref ManagedBy
        - Key: Type
          Value: RouteTable

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref AnswerKingPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref AnswerKingInternetGateway

  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AnswerKingSubnet
      RouteTableId: !Ref AnswerKingPrivateRouteTable

  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AnswerKingSubnet2
      RouteTableId: !Ref AnswerKingPrivateRouteTable

Outputs:
  AnswerKingVPCId:
    Description: AnswerKing VPC ID
    Value: !Ref AnswerKingVPC
    Export:
      Name: AnswerKingVPCID 

  Subnet1Id:
    Description: AnswerKing Subnet ID
    Value: !Ref AnswerKingSubnet
    Export:
      Name: Subnet1ID
  
  Subnet2Id:
    Description: AnswerKing Subnet 2 ID 
    Value: !Ref AnswerKingSubnet2
    Export:
      Name: Subnet2ID

